#!/bin/bash

echo Instalando recursos...
echo Actualizando Repositorios...

sudo apt-get update
echo Instalando recursos - Bridge Utils -...
sudo apt-get install bridge-utils
echo Instalando recursos - Net Tools -...
sudo apt-get install net-tools
echo Instalando recursos - Network Manger -...
sudo apt-get install network-manager
echo Instalando recursos - Hostapd -...
sudo apt-get install hostapd
echo Recursos instalados...
